### ISSUE TITLE
FAQ content doesn't apply to this project

### ISSUE THREAD

**Issue by nacmartin** [erikras/react-redux-promise-listener#1]
### Are you submitting a **bug report** or a **feature request**?

Bug Report

### What is the current behavior?

The faq doesn't apply to this project, it looks like copied from Final Form maybe 🤔 

https://github.com/erikras/react-redux-promise-listener/blob/master/docs/faq.md

**Comment by erikras** [comment]
🤣🤣🤣🤣🤣

No está en mi repo local. 😕🤷‍♂️

Too much _plisplay_. Merci. 🍸
